// Scenery, projectiles and particles in pixel art (session 6B). Scenery is drawn in shared colors;
// arrows wear their side's colors on the fletching; particles are white, to be tinted.

import { still, type Sprite } from './pixels';

export const PROP_ART = {
  tree: still([
    '.....kkkkkk.....',
    '...kklllllldkk..',
    '..klllllllllldk.',
    '.kllllllllldlddk',
    '.klllllldlllddDk',
    'kllldllllllddDDk',
    'klllllllldddDDDk',
    'kdllllldddddDDDk',
    'kddlllddddDDDDk.',
    '.kddddddDDDDDDk.',
    '.kDdddDDDDDDDk..',
    '..kkDDDDDDkkk...',
    '....kkWwWkk.....',
    '......kWwk......',
    '.....kWWwWk.....',
    '......kkkk......',
  ]),
  pine: still([
    '.......kk.......',
    '......kldk......',
    '.....klldDk.....',
    '....klllddDk....',
    '.....kldDDk.....',
    '....kllldDDk....',
    '...klllldddDk...',
    '..klllldddDDDk..',
    '....klldddDk....',
    '...kllldddDDk...',
    '..klllddddDDDk..',
    '.kllldddddDDDDk.',
    '.kkkkDDDDDDkkkk.',
    '......kWWk......',
    '......kWWk......',
    '.......kk.......',
  ]),
  bush: still([
    '..kkkkkk..',
    '.klllldlk.',
    'kllldllddk',
    'klldllddDk',
    'kddllddDDk',
    '.kdddDDDk.',
    '..kkkkkk..',
  ]),
  rock: still([
    '...kkkk...',
    '..koooOk..',
    '.kooooOOk.',
    'kooooOOOOk',
    'koOooOOOqk',
    '.kOOOOqqk.',
    '..kkkkkk..',
  ]),
  canyonRock: still([
    '...kkkk...',
    '..kppPPk..',
    '.kpppPPhk.',
    'kppPPPhhhk',
    'kPPPhhhhHk',
    '.khhhhHHk.',
    '..kkkkkk..',
  ]),
  crystal: still([
    '...k...',
    '..krk..',
    '..kRk..',
    '.krRvk.',
    '.kRrvk.',
    'krRrvVk',
    'kRrRvVk',
    'kRrvvVk',
    '.kvvVk.',
    '..kkk..',
  ]),
  shard: still([
    '...k...',
    '..kuk..',
    '..kuUk.',
    '.kuxUk.',
    '.kuuUk.',
    'kuuUUUk',
    'kUUUUUk',
    '.kkkkk.',
  ]),
  tuft: still(['..l..', 'l.l.l', 'ldldl', '.ddd.']),
  flower: still(['.x.', 'xgx', '.x.']),
  arrow: still(['LA.....k.', 'aAwwwwwmk', 'LA.....k.']),
  bolt: still(['.k.....k.', 'kMMMMMMmk', '.k.....k.']),
  spark: still(['..x..', '..x..', 'xxxxx', '..x..', '..x..']),
  dot: still(['.x.', 'xxx', '.x.']),
  puff: still(['..xxx..', '.xxxxx.', 'xxxxxxx', 'xxxxxxx', 'xxxxxxx', '.xxxxx.', '..xxx..']),
  chunk: still(['xxx', 'xx.']),
} satisfies Record<string, Sprite>;

export type PropId = keyof typeof PROP_ART;
